accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.user_registration, name="register"),
    path("profile/", views.edit_profile, name="edit_profile"),
    path(
        "change-password/", views.change_password, name="change_password"
    ),  # Новый маршрут
    # URL-адреса для сброса пароля
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views
from videos import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("videos/", include("videos.urls", namespace="videos")),
    path("<str:username>/", views.profile, name="profile"),
    path("<str:username>/subscription/", views.subscription, name="subscription"),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path(
        "<str:username>/likes/", views.liked_videos, name="liked_videos"
    ),  # Новая ссылка для лайкнутых видео
    # URL-адреса для сброса пароля
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

videos/urls.py
from django.urls import path

from . import views

app_name = "videos"


urlpatterns = [
    path("increment_views/", views.increment_views, name="increment_views"),
    path("video/<int:id>/", views.video, name="video"),
    path("add_video/", views.add_video, name="add_video"),
    path("check_censure/", views.check_censure_view, name="check_censure"),
    path("comment/", views.comment, name="comment"),
    path("remove/", views.remove, name="remove"),
    path("edit_video/<int:id>/", views.edit_video, name="edit_video"),
    path("like/", views.like, name="like"),
    path("home/", views.home, name="home"),
    path("subscribe/", views.subscribe, name="subscribe"),
    path("video/delete/<int:video_id>/", views.delete_video, name="delete_video"),
    path(
        "set_language/", views.set_language, name="set_language"
    ),  # Добавленный маршрут
    path("video_editor/", views.video_editor, name="video_editor"),
    path("video_editor/start", views.blur_data_api, name="blur_data_api"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


class CustomUserManager(BaseUserManager):
    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError("The Email must be set")
        if not username:
            raise ValueError("The Username must be set")

        user = self.model(username=username, email=self.normalize_email(email))
        user.set_password(password)
        user.is_active = True  # Убедитесь, что пользователь активен по умолчанию
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None):
        user = self.create_user(username, email, password=password)
        user.is_admin = True
        user.is_staff = True
        user.is_active = True  # Убедитесь, что суперпользователь активен
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser):
    username = models.CharField(max_length=300, unique=True)
    email = models.EmailField(max_length=255, unique=True, verbose_name="email address")
    avatar = models.ImageField(upload_to="avatars/", null=True, blank=True)
    is_active = models.BooleanField(default=True)  # Добавлено поле is_active
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.email

    def get_short_name(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser
from django import forms
from django.contrib.auth.forms import PasswordChangeForm

User = get_user_model()


class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Текущий пароль",
        widget=forms.PasswordInput(attrs={"class": "form-control input_login_style"}),
    )
    new_password1 = forms.CharField(
        label="Новый пароль",
        widget=forms.PasswordInput(attrs={"class": "form-control input_login_style"}),
    )
    new_password2 = forms.CharField(
        label="Поддтвердить пароль",
        widget=forms.PasswordInput(attrs={"class": "form-control input_login_style"}),
    )


class CustomUserCreationForm(forms.ModelForm):

    username = forms.CharField(
        label="Имя пользователя",
        max_length=100,
        min_length=5,
        widget=forms.TextInput(attrs={"class": "form-control input_login_style"}),
    )
    email = forms.EmailField(
        widget=forms.TextInput(attrs={"class": "form-control input_login_style"})
    )
    password1 = forms.CharField(
        label="Пароль",
        max_length=100,
        min_length=5,
        widget=forms.PasswordInput(attrs={"class": "form-control input_login_style"}),
    )
    password2 = forms.CharField(
        label="Подтвереждение пароля",
        max_length=100,
        min_length=5,
        widget=forms.PasswordInput(attrs={"class": "form-control input_login_style"}),
    )

    class Meta:
        model = CustomUser
        fields = ("username", "email", "password1", "password2")

    def clean_email(self):
        email = self.cleaned_data["email"]
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("Email is already registered.")
        return email

    def clean_username(self):
        username = self.cleaned_data["username"]
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Username is already in use.")
        return username

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        if commit:
            user.save()
        return user


class ProfileForm(forms.ModelForm):

    username = forms.CharField(
        label="Имя пользователя",
        max_length=100,
        min_length=5,
        widget=forms.TextInput(attrs={"class": "form-control input_login_style "}),
    )
    email = forms.EmailField(
        widget=forms.TextInput(attrs={"class": "form-control input_login_style "})
    )
    avatar = forms.ImageField(
        label="Изменить фото профиля",
        widget=forms.FileInput(attrs={"class": "form-control input_login_style "}),
    )

    class Meta:
        model = CustomUser
        fields = [
            "avatar",
            "username",
            "email",
        ]

    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            user = User.objects.exclude(pk=self.instance.pk).get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError("Username is already in use.")

    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            user = User.objects.exclude(pk=self.instance.pk).get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError("Email is already in use.")

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from datetime import datetime, timedelta
from .forms import CustomUserCreationForm, ProfileForm
from django.contrib.auth import update_session_auth_hash

from .forms import (
    CustomUserCreationForm,
    ProfileForm,
    CustomPasswordChangeForm,
)  # Добавьте CustomPasswordChangeForm здесь


def password_reset(request):

    page = request.GET.get("page")

    return render(request, "videos/password_reset_form.html", {})


def login_user(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            redirect_url = request.GET.get("next", "home")
            return redirect(redirect_url)
        else:
            messages.error(request, "Bad email or password")
    return render(request, "accounts/login.html", {})


def logout_user(request):
    logout(request)
    return redirect("accounts:login")


def user_registration(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(
                request,
                "Registration was successful",
                extra_tags="alert alert-success alert-dismissible fade show",  # noqa: E501
            )
            return redirect("home")
    else:
        form = CustomUserCreationForm()
    return render(request, "accounts/register.html", {"form": form})


def edit_profile(request):
    form = ProfileForm(instance=request.user)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(
                request,
                "Your profile was successfully updated ",
                extra_tags="alert alert-success alert-dismissible fade show",  # noqa: E501
            )
            return HttpResponseRedirect(
                reverse("profile", args=[str(request.user.username)])
            )  # noqa: E501

    return render(request, "accounts/edit_profile.html", {"form": form})


def change_password(request):
    if request.method == "POST":
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Сохраняем сессию пользователя
            messages.success(
                request,
                "Your password was successfully updated!",
                extra_tags="alert alert-success alert-dismissible fade show",
            )
            return redirect("accounts:edit_profile")
    else:
        form = CustomPasswordChangeForm(request.user)

    return render(request, "accounts/change_password.html", {"form": form})

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<div class="container container-windows">
	<div class="row">
		<div class="col-sm-6 offset-sm-3">
			<h2 class="mt-5 text-center">Сменить пароль</h2>

			{% if messages %}
			{% for message in messages %}
			<div {% if message.tags %} class="{{ message.tags }}" {% endif %}>
				{{ message }}
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			{% endfor %}
			{% endif %}

			<form action="{% url 'accounts:change_password' %}" method="post">
				{% csrf_token %}
				{% for field in form %}
				<div class="form-group">
					{{ field.errors }}
					{{ field.label_tag }}
					{{ field }}
				</div>
				{% endfor %}
				<input type="submit" value="Сменить пароль" class="btn  btn-secondary">
			</form>
		</div>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container ">
	<div class="gradient_block"></div>

	<div class="row container_modifacate">
		<div class="col-sm-6 offset-sm-3">

			<h2 class="mt-5 text-center">Редактирование профиля</h2>

			{% if messages %}
			{% for message in messages %}
			<div {% if message.tags %} class="{{ message.tags }}" {% endif %}>
				{{ message }}
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			{% endfor %}
			{% endif %}

			<form action="{% url 'accounts:edit_profile' %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}

				<div class="form-group text-center">
					{% if form.instance.avatar %}
					<img src="{{ form.instance.avatar.url }}" alt="Profile Picture"
						style="width: 100px; height: 100px; border-radius: 50%;">
					{% else %}
					<a href="{% url 'profile' page_user.username %}">
						<img src="{% static 'img/user.png' %}" class="user-profile-pic rounded-circle"
							alt="profile_pic" />
					</a>
					{% endif %}
				</div>

				<!-- Поле для загрузки аватара -->


				{% for field in form %}
				<div class="form-group dark-theme">
					{{ field.errors }}
					{{ field.label_tag }}
					{{ field }}
				</div>
				{% endfor %}

				<div class="login_reg_footer">
					<a href="{% url 'accounts:change_password' %}">Сменить пароль</a>
					<input type="submit" value="Подтвердить" class="btn btn-secondary">
				</div>

			</form>

		</div>
	</div>
</div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<div class="container container-windows">

	<div class="row">
		<div class="mt-5 col-md-6 offset-md-3">
			{% if messages %}
			<ul class="messages">
				{% for message in messages %}
				<li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
					{% endfor %}
			</ul>
			{% endif %}
			<form action="" method="post">
				{% csrf_token %}
				<div class="form-group ">
					<label for="email">Email</label>
					<input type="email" class="form-control input_login_style bg-dark text-light" name="email"
						placeholder="Введите емайл">
				</div>
				<div class="form-group ">
					<label for="password">Пароль</label>
					<input type="password" class="form-control  input_login_style bg-dark text-light" name="password"
						placeholder="Введите пароль">
				</div>
				<div class="login_reg_footer">
					<div class="reg_reset_link">
						<p>Нет аккаунта? <a href="{% url 'accounts:register' %}">Регистрация здесь</a></p>
						<p><a href="{% url 'accounts:password_reset' %}">Восстановить пароль</a></p>
					</div>
					<div class="btn_style"> <!-- Центрирование кнопки -->
						<button type="submit" class="btn btn_login btn-secondary">Подтвердить</button>
					</div>
				</div>
			</form>


		</div>
	</div>
</div>

</div>

{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<div class="container container-windows">
	<h2 class="mt-5">Пароль успешно сброшен</h2>
	<p>Ваш пароль был успешно изменен. Вы можете теперь <a href="{% url 'login' %}">войти</a> с новым паролем.</p>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<div class="container container-windows">
	<h2 class="mt-5">Сброс пароля</h2>
	<form method="post">
		{% csrf_token %}
		<div class="form-group">
			<label for="new_password1">Новый пароль</label>
			<input type="password" class="form-control input_login_style" name="new_password1" required
				placeholder="Введите новый пароль">
		</div>
		<div class="form-group">
			<label for="new_password2">Подтверждение нового пароля</label>
			<input type="password" class="form-control input_login_style" name="new_password2" required
				placeholder="Подтвердите новый пароль">
		</div>
		<button type="submit" class="btn btn-primary">Сбросить пароль</button>
	</form>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container container-windows">
	<h2 class="mt-5">Восстановление пароля</h2>
	<p>Введите адрес электронной почты, связанный с вашим аккаунтом. Мы отправим вам инструкции по сбросу пароля на этот
		email.</p>

	<div class="row">
		<div class="col-md-6 offset-md-3">
			{% if messages %}
			<ul class="alert alert-info">
				{% for message in messages %}
				<li>{{ message }}</li>
				{% endfor %}
			</ul>
			{% endif %}
			<form method="post">
				{% csrf_token %}
				<div class="form-group">
					<label for="email">Email</label>
					<input type="email" class="form-control" name="email" required autofocus
						placeholder="Введите ваш email">
				</div>
				<button type="submit" class="btn btn-primary">Сбросить пароль</button>
			</form>
			<p class="mt-2">Помните пароль? <a href="{% url 'login' %}">Войти</a></p>
		</div>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}

<div class="container container-windows">
	<div class="row">
		<div class="col-sm-6 offset-sm-3">

			<form action="" method="post">
				{% csrf_token %}
				{% for field in form %}
				<div class="form-group">
					{{ field.errors }}
					{{ field.label_tag }}
					{{ field }}
				</div>
				{% endfor %}
				<div class="login_reg_footer">
					<p>Уже есть аккаунт? <a href="{% url 'accounts:login' %}">Войдите здесь</a></p>
					<input type="submit" value="Подтвердить" class="btn btn-secondary">
				</div>

			</form>
		</div>
	</div>
</div>

{% endblock %}